### ISSUE TITLE
Wrong TextInputBar location while pushed from a controller with tab bar

### ISSUE THREAD

**Issue by kukushi** [slackhq/SlackTextViewController#136]
I'm using a `UITabBarController` with a `UINavigationController` holding a `UITableViewController` as root view controller.   
  
When I click on the cell and push a subclass of `SLKTextViewController` while set the `hideBottomBarWhenPushed` to yes, the text input bar locate 44 point(excatly the tab bar height) higher than the bottom fo the view and after about 1 second it suddenly go back to the real bottom.  

After research, I found it may be the issue of constraints and tab bar. Input text bar is located relate to the scollview, and it may effected by the bar bar. In  [this post](http://stackoverflow.com/questions/28724255/auto-layout-and-hide-bottom-bar-when-pushed "this post"), I found as workaround (*Select your "Navigation Controller" and in "Attribute Inspector" remove the checkmark from "Under Bottom Bars".*), but I don't really like that.

**Comment by solomon23** [comment]
I'm also seeing a bunch of weird problems putting this in a tab control.  One of which is the textinputbar is pushed down but if you hit the home button and open it back up, it'll render in the correct place but the tab background will be animated sort of oddly

**Comment by kevinrenskers** [comment]
Same problem here: UITabBarController, UINavigationController, the text input is shown under the tab bar. Go to background and back, and it shows up in the correct place. Right now the only workaround I could find is to use

```
- (BOOL)hidesBottomBarWhenPushed {
    return YES;
}
```
