### ISSUE TITLE
Custom Typing Indicator in Swift example does not display

### ISSUE THREAD

**Issue by timothytclee** [slackhq/SlackTextViewController#509]
#### Description

Custom Typing Indicator does not display in sample project Swift example
#### Steps to reproduce:
1. In Examples/Messenger-Swift/MessageViewController.swift, set DEBUG_CUSTOM_TYPING_INDICATOR = true
2. Run Messenger Swift
3. Typing Indicator does not show when icn_typing is tapped
### Actual result:

It appear that the failure occurs in the simulateUserTyping function here:
           guard let view = self.typingIndicatorProxyView as? TypingIndicatorView else {
                return
            }
### Expected result:

The same process works fine in the Objective C (Messenger Programatic) version of the sample project.

Wondering if there is something basic I'm getting wrong with the Swift implementation of this.  Thanks!

**Comment by algrid** [comment]
It looks like 
```
            self.registerClass(forTypingIndicatorView: TypingIndicatorView.classForCoder())
```
is called too late and default class is used instead.
