### ISSUE TITLE
weird behavior when processing unicode langauge for auto completion

### ISSUE THREAD

**Issue by intoxicated** [slackhq/SlackTextViewController#594]
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/SlackTextViewController/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/slackhq/SlackTextViewController/blob/master/.github/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
I tried to do auto completion with Korean but it sometime (happened after auto completion went to hide due to no match result).

#### Reproducible in:
* [x] This is reproducible in the sample project.
SlackTextViewController version:
iOS version(s): 10.2
Device(s): iphone 7 plus

#### Steps to reproduce:

1. register prefix for auto completion ("/" for this instance)
2. insert "/" and some korean to match result (assume there are items to display). And for example, there is match for "안녕"
3. insert "하". 

### Expected result:
expect to see text /안녕하 

### Actual result:
sometime it works but sometime it produced like /안녕ㅎㅏ (which is different from /안녕하, ㅎ and ㅏ didn't combine properly)

**Comment by blaswan** [comment]
Check this issue. https://github.com/slackhq/SlackTextViewController/issues/398

**Comment by intoxicated** [comment]
check my comment on #398
