### ISSUE TITLE
ContentView strange behaviour

### ISSUE THREAD

**Issue by lsvz** [slackhq/SlackTextViewController#596]
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/SlackTextViewController/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://github.com/slackhq/SlackTextViewController/blob/master/.github/CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
> ContentView's subview goes on top of textInputBar.

#### Reproducible in:
* [ ] This is reproducible in the sample project.
SlackTextViewController version: the latest one from git
iOS version(s): iOS 9/10
Device(s): iPhone 5s

#### Steps to reproduce:

1. Create a function testSubView() with the code
```
let view = UIView()
        view.translatesAutoresizingMaskIntoConstraints = false
        view.backgroundColor = .black
        
        let views = ["test" : view]
        
        self.textInputbar.contentView.addSubview(view)
        
        
        self.textInputbar.contentView.addConstraints(NSLayoutConstraint.constraints(withVisualFormat: "V:|[test(40)]|", options: NSLayoutFormatOptions(rawValue: 0), metrics: nil, views: views))
        self.textInputbar.contentView.addConstraints(NSLayoutConstraint.constraints(withVisualFormat: "H:|[test]|", options: NSLayoutFormatOptions(rawValue: 0), metrics: nil, views: views)))
```
2. Call it from `viewDidLoad` in your subclass of SLKTextViewController
3. See it works as expected
4. Call from any other function (in my example, it's a delegate of tableview's cell in my controller.)
5. It covers the `textInputBar`

### Expected result:
> e.g. `ContentView` should be under the `textInputBar`

### Actual result:
> e.g. `ContentView ` goes on top of `textInputBar`

### Attachments:
> expected:
![test1](https://cloud.githubusercontent.com/assets/7344370/25420715/c4b1d7a2-2a9c-11e7-862d-e08caa9d680d.jpg)
>actual:
![test2](https://cloud.githubusercontent.com/assets/7344370/25420736/de1a2c9e-2a9c-11e7-8e73-8d05bb19908a.jpg)

**Comment by inb4ohnoes** [comment]
I'm sure you've figured this out, but I was having the same issue and decided to just give my subview a height constant of 0 to begin with in viewDidLoad, then change it later as needed.

**Comment by inb4ohnoes** [comment]
Update: Turns out things break if you don't re-call layout stuff. To get things working (seemingly) 100%, you need to first call `layoutIfNeeded` on the `textInputBar` itself, then call `slk_updateViewConstraints`, which is a private method. Obviously this is wrong, but publicly defining `slk_updateViewConstraints` was the only thing that would get my views to lay out properly... Any ideas @dzenbot?

**Comment by JacobJT** [comment]
I had an issue with some cells appearing beneath my nav bar, even though the table was constrained to be smaller.

The solution was `tableView?.contentInset = .zero` and `tableView.clipsToBounds = true`

**Comment by inb4ohnoes** [comment]
yes, that’s why that solution is wrong even though it works.

**Comment by lsvz** [comment]
@inb4ohnoes Making `slk_updateViewConstraints` public and calling layoutIfNeeded before works as expected. Thanks!
@dzenbot I think you should make  `slk_updateViewConstraints`
