### ISSUE TITLE
SlackTextViewController Content Upside down

### ISSUE THREAD

**Issue by youTT001** [slackhq/SlackTextViewController#606]
i install pod SlackTextViewController in the project. I use UITableViewController but Content  Upside down .What i to do?
<a href="http://www.mx7.com/view2/zXxVRVZ505a9GHiF" target="_blank"><img border="0" src="http://www.mx7.com/i/2de/IZm3IY.png" /></a>

**Comment by youTT001** [comment]
i can fix, i use
self.inverted = YES;

**Comment by bogren** [comment]
You can read more about inverted mode here [docs](https://github.com/slackhq/SlackTextViewController#inverted-mode)

**Comment by youTT001** [comment]
@bogren thank you very much

**Comment by JacobJT** [comment]
You've inverted the table without inverting the cells. If you do one, you must do the other.
