### ISSUE TITLE
Textview is behind the keyboard

### ISSUE THREAD

**Issue by ShawnBaek** [slackhq/SlackTextViewController#615]
* [v ] I've read and understood the [Contributing guidelines](https://github.com/slackhq/SlackTextViewController/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [v ] I've read and agree to the [Code of Conduct](https://github.com/slackhq/SlackTextViewController/blob/master/.github/CODE_OF_CONDUCT.md).
* [ v] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
TextView is behind keyboard.

#### Reproducible in:
* [ ] This is reproducible in the sample project.
SlackTextViewController version:
iOS version(s): 10.3
Device(s): iphone 6

### Actual result:
When I tapped the textView then keyboard showing up. but textview is hidden.

related #605 problem

### Attachments:

<img width="376" alt="2017-08-12 8 19 26" src="https://user-images.githubusercontent.com/12643700/29240366-bee7a89a-7f9e-11e7-9985-c7daf90fb70b.png">

**Comment by johndoehelloworld** [comment]
+1

**Comment by ShawnBaek** [comment]
@johndoehelloworld I solved this problem. Override ViewDidAppear Func will affect this issue. Remove ViewDidAppear func in ViewController. But I don't know why this func affect this library.

**Comment by johndoehelloworld** [comment]
@ShawnBaek : I tried it, but it still doesn't want to work correctly all the time. Are you trying by bringing up the keyboard in your simulator? And every single time, you are seeing that input bar stays on top of the keyboard? In my case, most times the input bar is hidden, but sometimes, it does stick to the top of the keyboard. Thoughts?

**Comment by brod-ie** [comment]
@johndoehelloworld Make sure you include `super.viewDidAppear(animated)` within your `viewDidAppear` override

**Comment by tditchek** [comment]
This issue is happening for me on iOS 11.0.3. I have not overridden `viewDidAppear` in that view controller. Is this issue being addressed? If not, does anybody know of a workaround?

**Comment by brod-ie** [comment]
@ShawnBaek I can confirm this is happening on an iPhone 8 on iOS 11.1 without a view did appear override, please reopen the issue
![simulator screen shot - iphone 8 - 2017-11-10 at 08 05 34](https://user-images.githubusercontent.com/1520630/32648557-342732fc-c5ee-11e7-922b-784c6839b75e.png)

**Comment by brod-ie** [comment]
@ShawnBaek  @tditchek Did you find anything?

**Comment by tditchek** [comment]
@brod-ie Nothing yet. As far as I can tell, issue #605 is the cause, but I haven't been able to figure out a workaround yet. I cloned the repo to try to play around and see if I can figure out a fix but I'm not as advanced with Objective-C as I am with Swift so I'm having some trouble fixing it on my own.

**Comment by brod-ie** [comment]
@tditchek Thanks for the update, I also tried `self.presentKeyboard()` and `super.presentKeyboard()` to no luck until after view had appeared. Perhaps the keyboard show/hide notifications aren't bound until that event 🤔

**Comment by tditchek** [comment]
@brod-ie I added a fix to my forked SlackTextViewController project and it seems to work just fine now. I've submitted a pull request with the changes, but until @dzenbot approves it you can feel free to use my fork or inspect the above commit to add the changes locally on your own. good luck!

**Comment by brod-ie** [comment]
@tditchek Just used the fork and still no luck. When are you firing `textView.becomeFirstResponder()`, `viewDidLoad`/`viewWillAppear`/`viewDidAppear`? Or are you using `presentKeyboard()`?

**Comment by tditchek** [comment]
@brod-ie I'm not explicitly firing `textView.becomeFirstResponder()` or `presentKeyboard()`. I'm using the built-in tap gesture recognizer on the text view and it's working just fine. The keyboard is now pushing the textView up above it as it's supposed to. See the attached screenshot:

<img width="424" alt="screen shot 2017-11-16 at 1 34 19 pm" src="https://user-images.githubusercontent.com/3434973/32908957-3881b9dc-cad3-11e7-8d05-0756263c7887.png">

**Comment by brod-ie** [comment]
@tditchek By "built-in tap gesture recognizer on the text view" do you mean you're not automatically showing the keyboard on load/appear, but are letting the user tap in themselves? Or are you programmatically triggering that gesture recogniser? If so, how? Thanks 😊

**Comment by tditchek** [comment]
@brod-ie My use case required allowing the user to tap it on their own, but for argument's sake I just tried to add a `viewDidAppear` method with `textView.becomeFirstResponder` inside and it worked just fine. Since I use cocoa pods to manage my dependencies, I'm using my personal fork of the SlackTextViewController until @dzenbot or somebody else reviews my PR. If you're using cocoa pods you can add it like this 
`pod 'SlackTextViewController', :git => 'https://github.com/tditchek/SlackTextViewController', :branch => 'master'`
