### ISSUE TITLE
【dynamic cell height】 scroll jump problem

### ISSUE THREAD

**Issue by wyn15811017** [slackhq/SlackTextViewController#627]
I set tableViewCell with dynamic height.
- tableView.rowHeight = UITableViewAutomaticDimension
- tableView.estimatedRowHeight = 60

when I tried to use [scrollToRow] method to scroll to new message , I faced a problem that  scroll animated from last second or third message. If I input a message in same lines everytime, this problem was not occurred. 
<img width="376" alt="2017-09-25 23 50 38" src="https://user-images.githubusercontent.com/12561181/30814976-ad3c50fc-a24c-11e7-9d48-15e70137cb5a.png">
<img width="366" alt="2017-09-25 23 50 15" src="https://user-images.githubusercontent.com/12561181/30814977-ad8d8922-a24c-11e7-9da7-6df57a7b94ca.png">

**Comment by wyn15811017** [comment]
<img width="376" alt="2017-09-25 23 50 38" src="https://user-images.githubusercontent.com/12561181/30814875-62ece6e2-a24c-11e7-8c67-475a63a2e7c6.png">
<img width="376" alt="2017-09-25 23 50 38" src="https://user-images.githubusercontent.com/12561181/30814883-6765e732-a24c-11e7-80ba-1d17c2a5bfd5.png">

**Comment by wyn15811017** [comment]
<img width="366" alt="2017-09-25 23 50 15" src="https://user-images.githubusercontent.com/12561181/30814914-82a645a0-a24c-11e7-86b5-01edea837de6.png">

**Comment by cbedoy** [comment]
As suggestion, I had the similar problem, but I prefer to pre-calculate the height and read the value when TableView delegate call to Height

```
- (CGFloat) calculateTextHeight:(NSString *)messageText
{
    float   width                  = SCREEN_WIDTH;
    width                         -= CHAT_MESSAGE_MARGIN_LEFT;
    width                         -= CHAT_MESSAGE_MARGIN_RIGHT;
    
    CGSize size = CGSizeMake(width - OFFSET_IMAGE, NSIntegerMax);
    NSStringDrawingOptions options = (NSStringDrawingUsesLineFragmentOrigin|NSStringDrawingUsesFontLeading);
    
    NSAttributedString *attributedMessageText = [[NSAttributedString alloc] initWithString:messageText];
    
    
    attributedMessageText = [attributedMessageText formatWithEmojis];
    
    
    CGRect rect = [attributedMessageText boundingRectWithSize:size
                                                      options:options
                                                      context:nil];
    

    
    return rect.size.height + CHAT_MESSAGE_MARGIN_TOP + CHAT_MESSAGE_MARGIN_BOTTOM;
}


- (CGFloat) tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath
{
    if([tableView isEqual:self.tableView])
    {
        NSDictionary *cellModel = [self getModelForIndexPath:indexPath];
        return [self heightForCellModel:cellModel];
    }
    else
    {
        NSMutableDictionary *cellModel  = [[[self completionViewModel] valueForKeyPath:@"viewModel.completions"] objectAtIndex:[indexPath row]];
        return [cellModel[@"height"] floatValue];
    }
}
```
