### ISSUE TITLE
input bar not hidden at the first appearance when I set self.textInputbarHidden = YES;

### ISSUE THREAD

**Issue by ieliwb** [slackhq/SlackTextViewController#650]
![1](https://user-images.githubusercontent.com/2177409/32599806-3d217764-c503-11e7-8af8-1b6e9a904ad7.jpg)
- (void)viewDidLoad {
    [super viewDidLoad];
    
    self.bounces = YES;
    self.shakeToClearEnabled = YES;
    self.keyboardPanningEnabled = YES;
    self.shouldScrollToBottomAfterKeyboardShows = NO;
    self.inverted = NO;
    self.textInputbarHidden = YES;

   }

I want to hidden input bar  at the first appearance,when I click a button to show it,I set 
self.textInputbarHidden = YES;
in the viewDidLoad,but it also appearance and cannot be click,how can i to do it?

Thanks,every body help me

**Comment by burcsade** [comment]
That's because slk_updateViewConstraints overrides the height constraint that setTextInputbarHidden: method sets. Updating slk_updateViewConstraints as below fixes the problem.

```
- (void)slk_updateViewConstraints
{
    self.textInputbarHC.constant = self.textInputbar.isHidden ? 0.0 : self.textInputbar.appropriateHeight;
    self.scrollViewHC.constant = [self slk_appropriateScrollViewHeight];
    self.keyboardHC.constant = [self slk_appropriateKeyboardHeightFromRect:CGRectNull];
    
    if (_textInputbar.isEditing) {
        self.textInputbarHC.constant += self.textInputbar.editorContentViewHeight;
    }
    
    [super updateViewConstraints];
}
```

**Comment by ieliwb** [comment]
@burcsade thank you very much

**Comment by thomassnielsen** [comment]
@cerupcat I did! I ended up using this fork, which is has a few minor changes that made it work:
https://github.com/tarigancana/SlackTextViewController

I locked it to commit 0a58c4e656552f12a3969a6a896fd15a5d2aca44.

**Comment by cerupcat** [comment]
@thomassnielsen Great thanks! Will take a look.
