### ISSUE TITLE
Examples lack Collection View example

### ISSUE THREAD

**Issue by fran-sgd** [slackhq/SlackTextViewController#66]
The current set of example projects lack a collection view sample and the readme seems to have insufficient information on how to make this mode work.

**Comment by tamoyal** [comment]
I'm having trouble getting cells to load with the UICollectionView version and it seems there aren't examples anymore? My `cellForItemAt` is never being called although my `numberOfItemsInSection` is being called and returning a number above 0. I registered my cell using `self.collectionView.register(CommentCell.self, forCellWithReuseIdentifier: CommentCellIdentifier)` and init with:
```
    convenience init() {
        self.init(collectionViewLayout: UICollectionViewLayout())
    }
```

Any idea what step I could be missing?

**Comment by tamoyal** [comment]
FWIW - copying and pasting the `UICollectionView` version I made to a `UITableView` version almost directly (obviously converting the delegate methods) works so I really think a super basic example for UICollectionView would be very helpful
