### ISSUE TITLE
iOS 12 bottom bar is not hiding 

### ISSUE THREAD

**Issue by yarodevuci** [slackhq/SlackTextViewController#682]
I noticed on iOS 12 bottom bar is not hidden when requested. Also is not clickable either at least. Anyone else noticed that?

**Comment by 12789** [comment]
same issue.

iOS 12 on iPhone X

Before hide
![simulator screen shot - iphone xs - 2018-09-18 at 16 46 36](https://user-images.githubusercontent.com/244297/45722718-8eb1b480-bb62-11e8-812d-ae66ef563bb7.png)

After call self.setTextInputbarHidden(true, animated: true)
![simulator screen shot - iphone xs - 2018-09-18 at 16 46 14](https://user-images.githubusercontent.com/244297/45722719-92453b80-bb62-11e8-960c-705f01d363e7.png)

**Comment by yarodevuci** [comment]
@12789 Hi yes, helped for me too but without adding delay for my case. This is so weird..

**Comment by 10000TB** [comment]
same issue, the async fix also works for me, upvoted!
